# Generated by Django 5.0.2 on 2024-04-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_ciudad', models.CharField(max_length=70)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_municipio', models.CharField(max_length=70)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_calle', models.CharField(max_length=70)),
                ('nb_residencia', models.CharField(max_length=80)),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_cedula', models.IntegerField()),
                ('nb_nombre', models.CharField(max_length=50)),
                ('nb_apellido', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=60)),
                ('sexo', models.BooleanField()),
                ('fech_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('nu_telefono', models.IntegerField()),
                ('g_instruccion', models.CharField(max_length=100)),
                ('fech_registro', models.DateField()),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.direccion')),
            ],
        ),
    ]
